Controllers/homeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CLOUDY_PRE_IMPLEMENT.Controllers
{
    public class homeController : Controller
    {
        // GET: home
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult about()
        {

            return View("about");
        }
        public ActionResult service()
        {

            return View("service");
        }
        public ActionResult plan()
        {

            return View("plan");
        }
        public ActionResult domain()
        {

            return View("domain");
        }
        public ActionResult faq()
        {

            return View("faq");
        }
        public ActionResult blog()
        {

            return View("blog");
        }
        public ActionResult support()
        {

            return View("support");
        }
        public ActionResult contact()
        {

            return View("contact");
        }
        public ActionResult login()
        {

            return View("login");
        }
        public ActionResult register()
        {

            return View("register");
        }
        public ActionResult domainmanage()
        {

            return View("domainmanage");
        }
        public ActionResult process()
        {

            return View("process");
        }
        public ActionResult processorder()
        {

            return View("processorder");
        }
    }
}

Controllers/viewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CLOUDY_PRE_IMPLEMENT.Controllers
{
    public class viewController : Controller
    {
        // GET: view
        public ActionResult view()
        {
            return View();
        }
    }
}

Views/home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_Layout1.cshtml";
}

<div class="header">
    <div class="container">
        <div class="header_top">
            <div class="logo">
                <a href=""><img src="~/Assects/images/cloudysp.png" alt="" / width="50" height="50"><p> @Html.ActionLink("CLOUDY SPACE", "index", "home")</p></a>
            </div>
            <div class="cssmenu">
                <ul>
                    <li><a href="mailto:clodyspace12@gmail.com">info(at)cloudyspace.com</a></li>
                    <li class="active">@Html.ActionLink("LOGIN","login","home")</li>
                    <li>@Html.ActionLink("REGISTER","register","home")</li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="h_menu4">
            <!-- start h_menu4 -->
            <a class="toggleMenu" href="#">Menu</a>
            <ul class="nav">
                <li class="active">@Html.ActionLink("HOME","index","home")</li>
                <li> @Html.ActionLink("ABOUT US", "about", "home")</li>
                <li> @Html.ActionLink("SERVICE", "service", "home")</li>
                <li> @Html.ActionLink("PLANS", "plan", "home")</li>
                <li> @Html.ActionLink("DOMAIN", "domain", "home")</li>
                <li> @Html.ActionLink("FAQ", "faq", "home")</li>
                <li> @Html.ActionLink("BLOG", "blog", "home")</li>
                <li> @Html.ActionLink("SUPPORT", "support", "home")</li>
                <li> @Html.ActionLink("CONTACT", "contact", "home")</li>
            </ul>
            <script type="text/javascript" src="~/Assects/js/nav.js"></script>
        </div><!-- end h_menu4 -->
    </div>
</div>
<div class="banner">
    <div class="container">
        <!-- FlexSlider -->
        <section class="slider">
            <div class="flexslider">
                <ul class="slides">
                    <li>
                        <img src="~/Assects/images/backblack.jpg" class="img-responsive" alt="" />
                        
                        <div class="banner_desc">
                            <h1>CLOUD SERVICE</h1>
                            <h2>reputation-based trust management</h2>
                        </div>
                    </li>
                    <li>
                        <img src="~/Assects/images/bcblack3.jfif" class="img-responsive" alt="" />
                        <div class="banner_desc">
                            <h1>CLOUD SERVICE</h1>
                            <h2>reputation-based trust management</h2>
                        </div>
                    </li>
                    <li>
                        <img src="~/Assects/images/bcblack2.jpg" class="img-responsive" alt="" />
                        <div class="banner_desc">
                            <h1>CLOUD SERVICE</h1>
                            <h2>reputation-based trust management</h2>
                        </div>
                    </li>

                </ul>
            </div>
        </section>
        <!-- FlexSlider -->
    </div>
</div>
<div class="domain">
    <div class="container">
        <form class="search-form domain-search">
            <div class="two-fifth column first">
                <img src="~/Assects/images/magnifying.png" alt="" / width="50" height="50">
                <h2><span class="m_1">search your</span><br>domain</h2>
            </div>
            <div class="three-fifth column first">
                <input type="text" class="text" value="Enter your domain name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your domain name';}">
            </div>
            <div class="one-fifth column">
                <span class="selection-box">
                    <select class="domains valid" name="domains">
                        <option>Year(0-1 Year)</option>
                        <option>.com(From ₹700 / Year)</option>
                        <option>.info (From ₹580/ Year)</option>
                        <option>.net (From ₹450 / Year)</option>
                        <option>.org (From ₹400 / Year)</option>
                    </select>
                </span>
            </div>
            <div class="one-fifth column">
                <span class="selection-box">
                    <select class="domains valid" name="domains">
                        <option>.com(From ₹700 / Year)</option>
                        <option>.info(From ₹580 / Year)</option>
                        <option>.net (From ₹400 / Year)</option>
                        <option>.org (From ₹450 / Year)</option>
                    </select>
                </span>
            </div>
            <div class="one-fifth column">
                <input type="submit" value="Search">
            </div>
            <div class="clearfix"> </div>
        </form>
    </div>
</div>
<div class="benefit">
    <div class="container">
        <h4 class="tz-title-4 tzcolor-blue">
            <p class="tzweight_Bold"><span class="m_1">our<br></span>Benefits</p>
        </h4>
        <div class="box1">
            <div class="col-md-4 row_10">
                <ul class="service_grid">
                    <i class="s1"> </i>
                    <li class="desc">
                        <h3>99.9% Uptime</h3>
                        <p>99.9% uptime equals to a period of downtime of 1 minute and 26 seconds per day. 99.99% uptime equals to a period of downtime of less than 9 seconds per day. 99.999% uptime equals to a period of downtime of less than 1 second per day.</p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="service_grid">
                    <i class="s2"> </i>
                    <li class="desc">
                        <h3>24/7/365 Support</h3>
                        <p> used to emphasize that something happens or is important throughout every day of the year, with no pauses for weekends or holidays.</p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="service_grid">
                    <i class="s3"> </i>
                    <li class="desc">
                        <h3>Protect Your pc</h3>
                        <p>Windows Security (or Windows Defender Security Center in Windows 8 or early versions of Windows 10) is built in to Windows and provides real-time malware detection, prevention, and removal with cloud-delivered protection.</p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
        </div>
        <div class="box1">
            <div class="col-md-4">
                <ul class="service_grid">
                    <i class="s4"> </i>
                    <li class="desc">
                        <h3>DNS Control</h3>
                        <p> DNS Control provides the following benefits and enables you to: Monitor and apply policies to all DNS requests and responses, irrespective of the protocol and the encryption used</p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="service_grid">
                    <i class="s5"> </i>
                    <li class="desc">
                        <h3>Domain Transfer</h3>
                        <p>A domain transfer is the process of switching your domain name from one registrar to another. </p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="service_grid">
                    <i class="s6"> </i>
                    <li class="desc">
                        <h3>100% Security</h3>
                        <p>Certainly not. The only way to absolutely guarantee the security of any system is to shut down that system. Instead, practical security is about tradeoffs and ROI.</p>
                    </li>
                    <div class="clearfix"> </div>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="features">
    <div class="container">
        <div class="col-md-4">
            <h4 class="tz-title-4 tzcolor-blue">
                <p class="tzweight_Bold m_2"><span class="m_1">Now<br></span>What is Hot</p>
            </h4>
            <ul class="offer">
                <li><p class="m_3"><span class="m_4">Get Up to<br></span>50%</p></li>
                <li><p class="m_5">Off</p></li>
                <li class="last"><p class="m_6"><span class="m_7">Each<br></span>Hosting</p></li>
            </ul>
        </div>
        <div class="col-md-8 row_1">
            <h4 class="tz-title-4 tzcolor-blue">
                <p class="tzweight_Bold m_2"><span class="m_1">Our<br></span>Features</p>
            </h4>
            <div class="section_1">
                <div class="col_1_of_3 span_1_of_3">
                    <div class="list_1">
                        <ul>
                            <li><a href="">File Versioning</a></li>
                            <li><a href="">Automatic Synchronisation</a></li>
                            <li><a href="">Data Backups</a></li>
                            <li><a href="">Security</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col_1_of_3 span_1_of_3">
                    <div class="list_1">
                        <ul>
                            <li><a href="">Usability and accessibility</a></li>
                            <li><a href="">Cost-efficient</a></li>
                            <li><a href="">Convenient sharing of files</a></li>
                            <li><a href="">Multiple users</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col_1_of_3 span_1_of_3">
                    <ul><li class="active"><B><a href="plans.html">VIEW ALL</a></B></li></ul>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
<div class="domain">
    <div class="container">
        <form class="search-form domain-search">
            <div class="two-fifth signup column first">
                <img src="~/Assects/images/message.png" alt="" / width="50" height="50">
                <h2><span class="m_1">Sign Up Your</span><br>Newsletter</h2>
            </div>
            <div class="three-fifth searchbar column first">
                <input type="text" class="text" value="Enter your domain name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your domain name';}">
            </div>
            <div class="one-fifth col_2 ">
                <br><br>
                <p class="active"><b>@Html.ActionLink("DOMAIN MANAGE", "domainmanage", "home")</b></p>
                
            </div>
            <div class="clearfix"> </div>
        </form>
    </div>
</div>

Views/home/about.cshtml
@{
    ViewBag.Title = "about";
    Layout = "~/Views/shared/_Layout1.cshtml";
}

<div class="header">
    <div class="container">
        <div class="header_top">
            <div class="logo">
                <a href=""><img src="~/Assects/images/cloudysp.png" alt="" / width="50" height="50"><p> @Html.ActionLink("CLOUDY SPACE", "index", "home")</p></a>
            </div>
            <div class="cssmenu">
                <ul>
                    <li><a href="mailto:clodyspace12@gmail.com">info(at)cloudyspace.com</a></li>
                    <li class="active">@Html.ActionLink("LOGIN", "login", "home")</li>
                    <li>@Html.ActionLink("REGISTER", "register", "home")</li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="h_menu4">
            <!-- start h_menu4 -->
            <a class="toggleMenu" href="#">Menu</a>
            <ul class="nav">
                <li>@Html.ActionLink("HOME", "index", "home")</li>
                <li class="active"> @Html.ActionLink("ABOUT US", "about", "home")</li>
                <li> @Html.ActionLink("SERVICE", "service", "home")</li>
                <li> @Html.ActionLink("PLANS", "plan", "home")</li>
                <li> @Html.ActionLink("DOMAIN", "domain", "home")</li>
                <li> @Html.ActionLink("FAQ", "faq", "home")</li>
                <li> @Html.ActionLink("BLOG", "blog", "home")</li>
                <li> @Html.ActionLink("SUPPORT", "support", "home")</li>
                <li> @Html.ActionLink("CONTACT", "contact", "home")</li>
            </ul>
            <script type="text/javascript" src="~/Assects/js/nav.js"></script>

        </div><!-- end h_menu4 -->
    </div>
</div>
<div class="about">
    <div class="container">
        <h1>About Us<span class="m_1"><br>What we are</span></h1>
    </div>
</div>
<div class="about_grid">
    <div class="container">
        <h4 class="tz-title-4 tzcolor-blue">
            <p class="tzweight_Bold"><span class="m_1">our<br></span>Details</p>
        </h4>
        <div class="box3">
            <div class="col-md-6">
                <img src="~/Assects/images/cloudy2.jpg" class="img-responsive" alt="" width="500" height="600" />
            </div>
            <div class="col-md-6 row_2">
                <p class="m_8">The internet has drastically changed the IT industry. It not only connects a person with the world, but it also introduces new features every year. In the last decade, “cloud” was a new term tossed in the market, and soon it gained so much popularity that it now covers a large area of the industry.</p>
                <p class="m_9"><span class="quotes"></span> The main objective of the cloud, instead of saving data at local storage, the data of the user can be collected at some data center so the user could retrieve his or her data from any device.<span class="quotes-down"></span></p>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<div class="about_grid1">
    <div class="container">
        <h4 class="tz-title-4 tzcolor-blue">
            <p class="tzweight_Bold"><span class="m_1">Special<br></span>Offers</p>
        </h4>
        <div class="box4">
            <div class="col-md-6">
                <div class="col_1_of_2 span_1_of_2">
                    <img src="~/Assects/images/about pg.jpg" class="img-responsive" alt="" />
                </div>
                <div class="col_1_of_2 span_1_of_2">
                    <h3>Host Your Website</h3>
                    <p>
                        There are two ways to host a website: pay someone else to do it for you or you can do it yourself. Or, to put it more technically:
                        Use a hosting platform
                        Host locally
                    </p>
                    <div class="list_1 list_2">
                        <ul>
                            <li><a href="">Easy-to-use control panel.</a></li>
                            <li><a href="">Real reliability.</a></li>
                            <li><a href="">Room to grow.</a></li>
                            <li><a href="">Resources on demand.</a></li>
                        </ul><br /><br />
                    </div>
                    <p class="active">@Html.ActionLink("Host plans", "plan", "home")</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-6">
                <div class="col_1_of_2 span_1_of_2">
                    <img src="~/Assects/images/download.jfif" class="img-responsive" alt="" />
                </div>
                <div class="col_1_of_2 span_1_of_2">
                    <h3>Big Offers For Hosting</h3>
                    <p>It provides powerful website hosting services for small businesses to enterprises. It provides services for Website Building, WordPress Hosting, VPS Hosting, and Dedicated Hosting.</p>
                    <div class="list_1 list_2">
                        <ul>
                            <li><a href="">Public Cloud.</a></li>
                            <li><a href="">Physical Server.</a></li>
                            <li><a href="">secure process.</a></li>
                            <li><a href="">Domain network registration</a></li>
                        </ul><br /><br />
                    </div>
                    <p class="active">@Html.ActionLink("Hostplans", "plan", "home")</p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
</div>
<div class="domain">
    <div class="container">
        <form class="search-form domain-search">
            <div class="two-fifth signup column first">
                <img src="~/Assects/images/message.png" alt="" / width="50" height="50">
                <h2><span class="m_1">Sign Up Your</span><br>Newsletter</h2>
            </div>
            <div class="three-fifth searchbar column first">
                <input type="text" class="text" value="Enter your domain name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your domain name';}">
            </div>
            <div class="one-fifth col_2 ">
                <br><br>
                <p class="active"><b>@Html.ActionLink("DOMAIN MANAGE", "domainmanage", "home")</b></p>
            </div>
            <div class="clearfix"> </div>
        </form>
    </div>
</div>

Views/home/blog.cshtml
@{
    ViewBag.Title = "blog";
    Layout = "~/Views/shared/_Layout1.cshtml";
}

<div class="header">
    <div class="container">
        <div class="header_top">
            <div class="logo">
                <a href=""><img src="~/Assects/images/cloudysp.png" alt="" / width="50" height="50"><p> @Html.ActionLink("CLOUDY SPACE", "index", "home")</p></a>
            </div>
            <div class="cssmenu">
                <ul>
                    <li><a href="mailto:clodyspace12@gmail.com">info(at)cloudyspace.com</a></li>
                    <li class="active">@Html.ActionLink("LOGIN", "login", "home")</li>
                    <li>@Html.ActionLink("REGISTER", "register", "home")</li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="h_menu4">
            <!-- start h_menu4 -->
            <a class="toggleMenu" href="#">Menu</a>
            <ul class="nav">
                <li>@Html.ActionLink("HOME", "index", "home")</li>
                <li> @Html.ActionLink("ABOUT US", "about", "home")</li>
                <li> @Html.ActionLink("SERVICE", "service", "home")</li>
                <li> @Html.ActionLink("PLANS", "plan", "home")</li>
                <li> @Html.ActionLink("DOMAIN", "domain", "home")</li>
                <li> @Html.ActionLink("FAQ", "faq", "home")</li>
                <li class="active"> @Html.ActionLink("BLOG", "blog", "home")</li>
                <li> @Html.ActionLink("SUPPORT", "support", "home")</li>
                <li> @Html.ActionLink("CONTACT", "contact", "home")</li>
            </ul>
            <script type="text/javascript" src="~/Assects/js/nav.js"></script>
        </div><!-- end h_menu4 -->
    </div>
</div>
<body>
    <div class="about">
        <div class="container">
            <h1>Blog<span class="m_1"><br>Center</span></h1>
        </div>
    </div>
    <div class="about_grid">
        <div class="container">
            <h4 class="tz-title-4 tzcolor-blue">
                <p class="tzweight_Bold"><span class="m_1">Our<br></span>Blog</p>
            </h4><div class="about_grid">
                <center><img src="~/Assects/images/blogi.jpg" alt="" width="1000" height="500" /></center>
                <div class="col-md-6 login-right">
                    <h4 class="tz-title-5 tzcolor-blue">
                        <p class="tzweight_Bold"><span class="m_20">For Our Customers</span></p>
                    </h4>
                    <p>Give your feedback</p>
                    <form>
                        <div>
                            <span class="m_25">Name<label>*</label></span>
                            <input type="text">
                        </div>
                        <div>
                            <span class="m_25">Service Name<label>*</label></span>
                            <input type="text">
                        </div>
                        <div>
                            <span class="m_25">Email<label>*</label></span>
                            <input type="text">
                        </div>
                        <div>
                            <span class="m_25">Comment<label>*</label></span>
                            <input type="text">
                        </div>
                        <div>
                            <span class="m_25">
                                Rating Status
                                <select>
                                    <option>Select here</option>
                                    <option>Excellent</option>
                                    <option>Good</option>
                                    <option>Bad</option>
                                </select>
                            </span>


                        </div>
                        <br /><br />

                        <div class="one-fifth column">
                            <a href="mailto:clodyspace12@gmail.com"></b>SendYourFeedback</b></a><br><br>
                            <input type="submit" value="Reset"><br><br>
                        </div>
                    </form>
                </div>



                <div class="clearfix"> </div>
                </form>
            </div>
        </div>

Views/home/contact.cshtml
@{
    ViewBag.Title = "contact";
    Layout = "~/Views/shared/_Layout1.cshtml";
}
<div class="header">
    <div class="container">
        <div class="header_top">
            <div class="logo">
                <a href=""><img src="~/Assects/images/cloudysp.png" alt="" / width="50" height="50"><p> @Html.ActionLink("CLOUDY SPACE","index","home")</p></a>
            </div>
            <div class="cssmenu">
                <ul>
                    <li><a href="mailto:clodyspace12@gmail.com">info(at)cloudyspace.com</a></li>
                    <li class="active">@Html.ActionLink("LOGIN", "login", "home")</li>
                    <li>@Html.ActionLink("REGISTER", "register", "home")</li>
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div class="h_menu4">
            <!-- start h_menu4 -->
            <a class="toggleMenu" href="#">Menu</a>
            <ul class="nav">
                <li>@Html.ActionLink("HOME", "index", "home")</li>
                <li> @Html.ActionLink("ABOUT US", "about", "home")</li>
                <li> @Html.ActionLink("SERVICE", "service", "home")</li>
                <li> @Html.ActionLink("PLANS", "plan", "home")</li>
                <li> @Html.ActionLink("DOMAIN", "domain", "home")</li>
                <li> @Html.ActionLink("FAQ", "faq", "home")</li>
                <li> @Html.ActionLink("BLOG", "blog", "home")</li>
                <li> @Html.ActionLink("SUPPORT", "support", "home")</li>
                <li class="active"> @Html.ActionLink("CONTACT", "contact", "home")</li>
            </ul>
            <script type="text/javascript" src="~/Assects/js/nav.js"></script>
        </div><!-- end h_menu4 -->
    </div>
</div>
<div class="about">
    <div class="container">
        <h1>contact<span class="m_1"><br>Center</span></h1>
    </div>
</div>
<div class="support_box">
    <div class="container">
        <div class="col-md-6">
            <h4 class="tz-title-4 tzcolor-blue">
                <p class="tzweight_Bold"><span class="m_1">Info<br></span>Contact Us</p>
            </h4>
            <p class="text1">From the below informations you can contact us.</p>
            <div class="contact_address1">
                <div class="col_1_of_2 span_1_of_2 row_5">
                    <h4 class="tz-title-6">
                        <p><span class="m_21">Address</span></p>
                    </h4>
                    <p>Kannampalayam</p>
                </div>
                <div class="col_1_of_2 span_1_of_2 row_5">
                    <h4 class="tz-title-6">
                        <p><span class="m_21">Email Address</span></p>
                    </h4>
                    <p><a href="malito:mail@demolink.org">General : info(at)cloudyspace.com</a></p>
                    <p><a href="malito:mail@demolink.org">Office : info(at)cloudyspace.com</a></p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="contact_address1">
                <div class="col_1_of_2 span_1_of_2 row_5">
                    <h4 class="tz-title-6">
                        <p><span class="m_21">Phone</span></p>
                    </h4>
                    <p>Mobile : +874 1478 74755</p>
                </div>
                <div class="col_1_of_2 span_1_of_2 row_5">
                    <h4 class="tz-title-6">
                        <p><span class="m_21">Social Media</span></p>
                    </h4>
                    <ul class="contact_social">
                        <li><a href=""> <i class="fb"> </i> </a></li>
                        <li><a href=""><i class="tw"> </i> </a></li>
                        <li><a href=""><i class="google"> </i> </a></li>
                        <li><a href=""><i class="utube"> </i> </a></li>
                        <li><a href=""><i class="linkedin"> </i> </a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="col-md-6 contact_right">
            <h4 class="tz-title-4 tzcolor-blue">
                <p class="tzweight_Bold"><span class="m_1">Contact<br></span>Form</p>
            </h4>

            <input type="text" class="text" name="name" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
            <input type="text" class="text" name="email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}">
            <input type="text" class="text" nzme="sub" value="Subject" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Subject';}">
            <textarea value="Comment" name="comment" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Comment</textarea>
            <input type="submit" value="Submit">
            </form>
            </form>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1192.2860489934303!2d77.08429268954829!3d10.999295068065843!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba85695d582db7b%3A0x55286f9c43c3294d!2sKalaignarKarunanidhi%20Institute%20Of%20Technology!5e1!3m2!1sen!2sin!4v1684403152089!5m2!1sen!2sin" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

Views/view/view.cshtml
@{
    ViewBag.Title = "view";
    Layout = "~/Views/shared/_Layout1.cshtml";
}

<h2>view</h2>